### PR TITLE
Product Base Price

### PR DESCRIPTION
**Pull request by forellana-digithinkit**
--- Added
- CHANGELOG file to keep track of changes.
- Added spinner to awc template loading process.

--- Changed
- Passing `base_price` through awesome cart to keep track of customer "savings"
- Updated AwesomeCartJS lib to pass base_price through templates and requests.
- Moved full cart template to file at `/awesome_cart/public/awc-templates/full-cart.html`
- Moved listing item template to file at `/awesome_cart/public/awc-templates/listing-item-generic.html`
- During `addToCart` operation, we made sure to update the item `base_price` to keep consistent data on cart.

See similar PR where I've moved product awc template to repo: https://github.com/DigiThinkIT/jhaudio_customizations/pull/1023

To test change the following templates:

- `/desk#Form/AWC%20Template/cart-full` to:

`{{{template "/assets/awesome_cart/awc-templates/full-cart.html" this }}}`

- `/desk#Form/AWC%20Template/Listing%20Widget%20IEMs` to:

`{{{template "/assets/awesome_cart/awc-templates/listing-item-generic.html" this }}}`

base-price-listing

### CODE REVIEW

**Comment by vjFaLk** [comment]
@forellana-digithinkit Why have separate CHANGELOG file? We do list out details on the PR itself

**Comment by Alchez** [comment]
Price changes appear correctly, although the CSS is slightly borked.

<hr>

**On the product listing page:**
image

<hr>

**On the cart:**
image

**Comment by neilLasrado** [comment]
@forellana-digithinkit Also add 'You Save $xyz (xx%)' below the price maybe ? Reminding the user that he saves money usually tricks him to buy stuff.

**Comment by forellana-digithinkit** [comment]
Added "You Saved" labels to product listing:

yousave-template-listing

Product details version is on jhaudio_customizations
@neilLasrado

**Pull request merged**
